app:
  name: '@name@'
  description: '@description@'
  version: '@version@'

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/bioskop_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html