server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgres://localhost:5432/
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

