app:
  name: '@name@'
  description: '@description@'
  version: '@version@'

  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    exp: 18000000

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/bioskop_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver