app:
  name: '@name@'
  description: '@description@'
  version: '@version@'

  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    exp: 600000 # 10 Minute 
    #18000000 # 5 Hours 

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://containers-us-west-87.railway.app:6048/railway
    #postgresql://localhost:5432/bioskop_db
    username: postgres
    password: ocwBVGOXv2pVZ9gdqBvr
    driver-class-name: org.postgresql.Driver